package com.jost.invernadero.codegen.validator;

import com.jost.invernadero.codegen.model.EntityDefinition;
import com.jost.invernadero.codegen.model.FieldDef;
import com.jost.invernadero.codegen.model.RelationDef;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

public class EntityDefinitionValidator {

    private static final Pattern PASCAL_CASE = Pattern.compile("^[A-Z][A-Za-z0-9]*$");
    private static final Pattern SNAKE_CASE = Pattern.compile("^[a-z][a-z0-9_]*$");

    public ValidationReport validate(EntityDefinition definition) {
        List<ValidationReport.Error> errors = new ArrayList<>();
        List<ValidationReport.Warning> warnings = new ArrayList<>();

        validateRootNames(definition, errors);
        Map<String, Integer> fieldIndexes = validateFields(definition.fields(), errors, warnings);
        validateRelations(definition.relations(), fieldIndexes.keySet(), errors);

        return new ValidationReport(errors, warnings);
    }

    private void validateRootNames(EntityDefinition definition, List<ValidationReport.Error> errors) {
        if (!matches(PASCAL_CASE, definition.name())) {
            errors.add(error("$.name", "name must be PascalCase"));
        }
        if (!matches(SNAKE_CASE, definition.tableName())) {
            errors.add(error("$.tableName", "tableName must be snake_case"));
        }
    }

    private Map<String, Integer> validateFields(
            List<FieldDef> fields,
            List<ValidationReport.Error> errors,
            List<ValidationReport.Warning> warnings) {
        Map<String, Integer> fieldIndexes = new HashMap<>();
        boolean hasId = false;

        for (int index = 0; index < fields.size(); index++) {
            FieldDef field = fields.get(index);
            String normalizedName = normalize(field.name());
            if ("id".equals(normalizedName)) {
                hasId = true;
            }

            Integer previousIndex = fieldIndexes.putIfAbsent(normalizedName, index);
            if (previousIndex != null) {
                errors.add(error("$.fields[%d].name".formatted(index),
                        "field name duplicates $.fields[%d].name".formatted(previousIndex)));
            }

            if ("String".equals(field.type()) && field.length() == null) {
                warnings.add(warning("$.fields[%d].length".formatted(index),
                        "String field should define length"));
            }
        }

        if (!hasId) {
            warnings.add(warning("$.fields", "No id field found; generator will add an autogenerated Long id"));
        }

        return fieldIndexes;
    }

    private void validateRelations(
            List<RelationDef> relations,
            Set<String> fieldNames,
            List<ValidationReport.Error> errors) {
        Set<String> relationNames = new HashSet<>();

        for (int index = 0; index < relations.size(); index++) {
            RelationDef relation = relations.get(index);
            String normalizedName = normalize(relation.name());

            if (!relationNames.add(normalizedName)) {
                errors.add(error("$.relations[%d].name".formatted(index),
                        "relation name must be unique"));
            }
            if (fieldNames.contains(normalizedName)) {
                errors.add(error("$.relations[%d].name".formatted(index),
                        "relation name collides with a field name"));
            }

            validateRelationOwnership(relation, index, errors);
        }
    }

    private void validateRelationOwnership(
            RelationDef relation,
            int index,
            List<ValidationReport.Error> errors) {
        boolean hasMappedBy = hasText(relation.mappedBy());
        boolean hasJoinColumn = hasText(relation.joinColumn());

        switch (relation.type()) {
            case "OneToMany" -> {
                require(hasMappedBy, "$.relations[%d].mappedBy".formatted(index),
                        "mappedBy is required for inverse OneToMany relations", errors);
                forbid(hasJoinColumn, "$.relations[%d].joinColumn".formatted(index),
                        "joinColumn is not allowed for inverse OneToMany relations", errors);
            }
            case "ManyToOne" -> {
                require(hasJoinColumn, "$.relations[%d].joinColumn".formatted(index),
                        "joinColumn is required for owning ManyToOne relations", errors);
                forbid(hasMappedBy, "$.relations[%d].mappedBy".formatted(index),
                        "mappedBy is not allowed for owning ManyToOne relations", errors);
            }
            case "OneToOne" -> {
                if (hasJoinColumn == hasMappedBy) {
                    errors.add(error("$.relations[%d]".formatted(index),
                            "OneToOne relations must define exactly one of joinColumn or mappedBy"));
                }
            }
            case "ManyToMany" -> forbid(hasJoinColumn, "$.relations[%d].joinColumn".formatted(index),
                    "joinColumn is not allowed for ManyToMany relations", errors);
            default -> errors.add(error("$.relations[%d].type".formatted(index),
                    "unsupported relation type: " + relation.type()));
        }
    }

    private static void require(
            boolean condition,
            String path,
            String message,
            List<ValidationReport.Error> errors) {
        if (!condition) {
            errors.add(error(path, message));
        }
    }

    private static void forbid(
            boolean condition,
            String path,
            String message,
            List<ValidationReport.Error> errors) {
        if (condition) {
            errors.add(error(path, message));
        }
    }

    private static boolean matches(Pattern pattern, String value) {
        return value != null && pattern.matcher(value).matches();
    }

    private static boolean hasText(String value) {
        return value != null && !value.isBlank();
    }

    private static String normalize(String value) {
        return value == null ? "" : value.toLowerCase(Locale.ROOT);
    }

    private static ValidationReport.Error error(String path, String message) {
        return new ValidationReport.Error(path, message);
    }

    private static ValidationReport.Warning warning(String path, String message) {
        return new ValidationReport.Warning(path, message);
    }
}
